# Generated by Django 5.0.4 on 2024-04-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('IDAsignacion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Presenta', models.DateField(blank=True, null=True, verbose_name='Fecha_Presenta')),
                ('Fecha_Asigna', models.DateField(blank=True, null=True, verbose_name='Fecha_Asigna')),
                ('Fecha_Proxima', models.DateField(blank=True, null=True, verbose_name='Fecha_Proxima')),
            ],
        ),
        migrations.CreateModel(
            name='cliente_proveedor_cliente_proveedor',
            fields=[
                ('IDClientes_Proveedores', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='declaracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('tiempo', models.DecimalField(decimal_places=0, default=30, max_digits=5, verbose_name='Tiempo')),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observacion')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='planillas_planilla_funcionarios',
            fields=[
                ('IDPlanilla_Funcionarios', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
