# Generated by Django 5.0.3 on 2024-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='declaracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('tiempo', models.DecimalField(decimal_places=0, default=30, max_digits=5, verbose_name='Tiempo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observacion')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
