# Generated by Django 5.0.4 on 2024-04-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracion',
            old_name='id',
            new_name='IDDeclaracion',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='IDClientes_Proveedores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente_proveedor_cliente_proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='IDDeclaracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.declaracion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacion',
            name='IDPlanilla_Funcionarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.planillas_planilla_funcionarios'),
            preserve_default=False,
        ),
    ]
