# Generated by Django 5.0.3 on 2024-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
