# Generated by Django 5.0.4 on 2024-04-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_id_declaracion_iddeclaracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='Direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='Email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
