# Generated by Django 5.0.4 on 2024-04-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_cliente_proveedor_cliente_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='Fecha_Ultimo_Movimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
