# Generated by Django 5.0.4 on 2024-04-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_cliente_proveedor_cliente_proveedor_fecha_ultimo_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente_proveedor_cliente_proveedor',
            old_name='Fecha_Ultimo_Movimiento',
            new_name='Fecha_Ult_Movimiento',
        ),
    ]
