# Generated by Django 5.0.4 on 2024-04-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_rename_fecha_ultimo_movimiento_cliente_proveedor_cliente_proveedor_fecha_ult_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
