# Generated by Django 5.0.4 on 2024-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_cliente_proveedor_cliente_proveedor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='correo',
            field=models.BooleanField(default=False),
        ),
    ]
