# Generated by Django 5.0.4 on 2024-04-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_asignacion_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaracion_Clientes',
            fields=[
                ('IDDeclaracion_Clientes', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Asigna', models.DateField(blank=True, null=True, verbose_name='Fecha_Asigna')),
                ('estado', models.BooleanField(default=False)),
                ('observacion', models.CharField(max_length=180)),
                ('IDClientes_Proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente_proveedor_cliente_proveedor')),
                ('IDDeclaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.declaracion')),
                ('IDPlanilla_Funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.planillas_planilla_funcionarios')),
            ],
        ),
    ]
