# Generated by Django 5.0.4 on 2024-04-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_declaracion_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracion_clientes',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='declaracion_clientes',
            old_name='observacion',
            new_name='Observacion',
        ),
    ]
