# Generated by Django 5.0.4 on 2024-05-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_remove_declaracion_clientes_idplanilla_funcionarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracion_clientes',
            old_name='IDDeclaracion',
            new_name='IDDeclaracion_id',
        ),
    ]
