# Generated by Django 5.0.4 on 2024-05-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_rename_iddeclaracion_declaracion_clientes_iddeclaracion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaracion_clientes',
            old_name='IDDeclaracion_id',
            new_name='IDDeclaracion',
        ),
    ]
