# Generated by Django 5.0.4 on 2024-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_planillas_planilla_funcionarios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='Iniciada',
            field=models.BooleanField(default=False),
        ),
    ]
