# Generated by Django 5.0.4 on 2024-05-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_asignacion_iniciada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='Suspendida',
            field=models.BooleanField(default=False),
        ),
    ]
