# Generated by Django 5.0.4 on 2024-06-07 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_asignacion_suspendida'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendario_tributario',
            fields=[
                ('IDCalendario_tributario', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Presenta', models.DateField(blank=True, null=True, verbose_name='Fecha_Presenta')),
                ('Observaciones', models.TextField(blank=True, verbose_name='Observacion')),
                ('IDClientes_Proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente_proveedor_cliente_proveedor')),
                ('IDDeclaracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.declaracion')),
                ('IDPlanilla_Funcionarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.planillas_planilla_funcionarios')),
            ],
        ),
    ]
