# Generated by Django 5.0.4 on 2024-07-05 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_remove_calendario_tributario_idclientes_proveedores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='Tipo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historico_declaraciones',
            name='Fecha_Sistema',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha_Sistema'),
        ),
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='Fecha_Final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Final'),
        ),
        migrations.CreateModel(
            name='Declaraciones_Tipo_Cliente',
            fields=[
                ('IDDeclaraciones_Tipo_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Condicion', models.IntegerField(blank=True, verbose_name='Condicion')),
                ('Fch_Solicitud', models.DateField(blank=True, null=True, verbose_name='Fch_Solicitud')),
                ('Numero_Solicitud', models.CharField(max_length=50)),
                ('Fch_Autorizacion', models.DateField(blank=True, null=True, verbose_name='Fch_Autorizacion')),
                ('Numero_Autoriza', models.CharField(max_length=50)),
                ('NombreAdcional', models.CharField(max_length=100)),
                ('Legal', models.CharField(max_length=100)),
                ('Tarifa', models.IntegerField(blank=True, verbose_name='Tarifa')),
                ('Fch_Vence', models.DateField(blank=True, null=True, verbose_name='Fch_Vence')),
                ('tramitado', models.CharField(max_length=100)),
                ('Fch_Sistema', models.DateTimeField(auto_now_add=True)),
                ('IDClientes_Proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente_proveedor_cliente_proveedor')),
            ],
        ),
    ]
