# Generated by Django 5.0.4 on 2024-07-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0024_declaraciones_tipo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declaraciones_tipo',
            old_name='Descipcion',
            new_name='Descripcion',
        ),
    ]
