# Generated by Django 5.0.4 on 2024-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0026_detalle_declaracion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_declaracion_tipo',
            name='Informa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='detalle_declaracion_tipo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
