# Generated by Django 5.0.4 on 2024-07-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0027_detalle_declaracion_tipo_informa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_Declaracion_Tipo',
            new_name='Detalle_Declaraciones_Tipo',
        ),
    ]
