# Generated by Django 5.0.4 on 2024-07-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0028_rename_detalle_declaracion_tipo_detalle_declaraciones_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detalle_Declaraciones_Tipo',
        ),
    ]
