# Generated by Django 5.0.4 on 2024-07-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0029_delete_detalle_declaraciones_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Declaracion_Tipo',
            fields=[
                ('IDDetalle_Declaracion_Tipo', models.AutoField(primary_key=True, serialize=False)),
                ('Detalle', models.CharField(max_length=255)),
                ('Fecha_solicitud', models.DateField(blank=True, verbose_name='Fecha_Emision')),
                ('Numero_solicitud', models.CharField(max_length=55)),
                ('Fecha_autorizacion', models.DateField(blank=True, verbose_name='Fecha_autorizacion')),
                ('Numero_aurotizado', models.CharField(max_length=60)),
                ('Fecha_vencimiento', models.DateField(blank=True, verbose_name='Fecha_vencimiento')),
                ('Fundamento_Legal', models.CharField(max_length=150)),
                ('observaciones', models.CharField(max_length=255)),
                ('Otorgadopor', models.CharField(max_length=100)),
                ('Recordar_antes', models.IntegerField(blank=True, verbose_name='Recordar_antes')),
                ('Recordar_cada', models.IntegerField(blank=True)),
                ('Estado', models.BooleanField(default=True)),
                ('Correo_Notificar', models.CharField(max_length=255)),
                ('Responsable', models.CharField(max_length=200)),
                ('Porcentaje', models.CharField(max_length=100)),
                ('Informa', models.IntegerField(default=0, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('IDClientes_Proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cliente_proveedor_cliente_proveedor')),
            ],
        ),
    ]
