# Generated by Django 5.0.4 on 2024-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0030_detalle_declaracion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_declaracion_tipo',
            name='Fecha_autorizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_autorizacion'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_tipo',
            name='Fecha_solicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Emision'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_tipo',
            name='Fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_vencimiento'),
        ),
    ]
