# Generated by Django 5.0.4 on 2024-07-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0031_alter_detalle_declaracion_tipo_fecha_autorizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_declaracion_tipo',
            name='IDDeclaraciones_Tipo',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='libreria.declaraciones_tipo'),
            preserve_default=False,
        ),
    ]
