# Generated by Django 5.0.4 on 2024-07-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0032_detalle_declaracion_tipo_iddeclaraciones_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_declaracion_tipo',
            old_name='Numero_aurotizado',
            new_name='Numero_autorizado',
        ),
    ]
