# Generated by Django 5.0.4 on 2024-07-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0034_rename_imagen_detalle_declaracion_tipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_declaracion_tipo',
            name='Fecha_Recordatorio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha_Recordatorio'),
        ),
    ]
