# Generated by Django 5.0.4 on 2024-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0036_alter_historico_declaraciones_fecha_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='rectificativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historico_declaraciones',
            name='rectificativa',
            field=models.BooleanField(default=False),
        ),
    ]
