# Generated by Django 5.0.4 on 2024-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0037_declaracion_rectificativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracion',
            name='rectificativa',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Rectificativa',
            field=models.BooleanField(default=False),
        ),
    ]
