# Generated by Django 5.0.4 on 2024-07-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0038_remove_declaracion_rectificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='Numero_Comprobante',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
