# Generated by Django 5.0.4 on 2024-07-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0040_alter_historico_declaraciones_numero_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='Numero_Comprobante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
