# Generated by Django 5.0.4 on 2024-07-31 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0041_alter_historico_declaraciones_numero_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_declaraciones',
            name='IDCalendario_tributario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.calendario_tributario'),
        ),
    ]
