# Generated by Django 5.0.4 on 2024-08-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0043_asignacion_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_declaraciones',
            name='Mes',
            field=models.IntegerField(default=0, verbose_name='Mes'),
        ),
    ]
