# Generated by Django 5.0.4 on 2024-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0044_historico_declaraciones_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_Corporativo',
            fields=[
                ('IDConfiguracion_Corporativo', models.AutoField(primary_key=True, serialize=False)),
                ('Detalle', models.CharField(max_length=180, verbose_name='Detalle')),
                ('Observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
