# Generated by Django 5.0.4 on 2024-08-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0045_configuracion_corporativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='IDConfiguracion_Corporativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.configuracion_corporativo'),
            preserve_default=False,
        ),
    ]
