# Generated by Django 5.0.4 on 2024-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0047_parametros_declaraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='Clave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave'),
        ),
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='IDCia',
            field=models.IntegerField(blank=True, null=True, verbose_name='IDCia'),
        ),
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='Nombre_Base',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre_Base'),
        ),
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='Puerto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Puerto'),
        ),
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='Server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IDCia'),
        ),
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='Usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario'),
        ),
    ]
