# Generated by Django 5.0.4 on 2024-08-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0048_parametros_declaraciones_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros_declaraciones',
            name='Server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Server'),
        ),
    ]
