# Generated by Django 5.0.4 on 2024-08-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0049_alter_parametros_declaraciones_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros_declaraciones',
            name='Ubicacion_logo',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
