# Generated by Django 5.0.4 on 2024-08-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0050_alter_parametros_declaraciones_ubicacion_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('IDBitacora', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Sistema', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('Proceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proceso')),
                ('Descripcion', models.TextField()),
                ('Observacones', models.TextField()),
                ('Modulo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modulo')),
            ],
        ),
    ]
