# Generated by Django 5.0.4 on 2024-08-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0051_bitacora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='Observacones',
            new_name='Observaciones',
        ),
    ]
