# Generated by Django 5.0.4 on 2024-08-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0052_rename_observacones_bitacora_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaraciones_tipo',
            name='Observacion',
            field=models.TextField(),
        ),
    ]
