# Generated by Django 5.0.4 on 2024-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0053_alter_declaraciones_tipo_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico_declaraciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
