# Generated by Django 5.0.4 on 2024-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0055_alter_historico_declaraciones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagenes/acuse/', verbose_name='Imagen'),
        ),
    ]
