# Generated by Django 5.0.4 on 2024-08-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0056_alter_historico_declaraciones_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros_declaraciones',
            name='Calendario',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Calendario'),
        ),
    ]
