# Generated by Django 5.0.4 on 2024-09-11 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0057_parametros_declaraciones_calendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='IDDeclaracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.declaracion'),
        ),
    ]
