# Generated by Django 5.0.4 on 2024-09-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0058_alter_asignacion_iddeclaracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='IDDeclaracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.declaracion'),
        ),
    ]
