# Generated by Django 5.0.4 on 2024-09-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0059_alter_asignacion_iddeclaracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='IDClientes_Proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.cliente_proveedor_cliente_proveedor'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='IDDeclaracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.declaracion'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='IDPlanilla_Funcionarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.planillas_planilla_funcionarios'),
        ),
        migrations.AlterField(
            model_name='calendario_tributario',
            name='IDDeclaracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.declaracion'),
        ),
        migrations.AlterField(
            model_name='cliente_proveedor_cliente_proveedor',
            name='IDConfiguracion_Corporativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.configuracion_corporativo'),
        ),
        migrations.AlterField(
            model_name='declaracion_clientes',
            name='IDClientes_Proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.cliente_proveedor_cliente_proveedor'),
        ),
        migrations.AlterField(
            model_name='declaracion_clientes',
            name='IDDeclaracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.declaracion'),
        ),
        migrations.AlterField(
            model_name='declaraciones_tipo_cliente',
            name='IDClientes_Proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.cliente_proveedor_cliente_proveedor'),
        ),
        migrations.AlterField(
            model_name='declaraciones_tipo_cliente',
            name='IDDeclaraciones_Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.declaraciones_tipo'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_tipo',
            name='IDClientes_Proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.cliente_proveedor_cliente_proveedor'),
        ),
        migrations.AlterField(
            model_name='detalle_declaracion_tipo',
            name='IDDeclaraciones_Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.declaraciones_tipo'),
        ),
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='IDCalendario_tributario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreria.calendario_tributario'),
        ),
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='IDClientes_Proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.cliente_proveedor_cliente_proveedor'),
        ),
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='IDDeclaracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.declaracion'),
        ),
        migrations.AlterField(
            model_name='historico_declaraciones',
            name='IDPlanilla_Funcionarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.planillas_planilla_funcionarios'),
        ),
    ]
