# Generated by Django 5.0.4 on 2024-09-18 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0060_alter_asignacion_idclientes_proveedores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('IDPermisos', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Sistema', models.DateTimeField(auto_now_add=True)),
                ('Nombre_Permiso', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre_Permiso')),
                ('Formulario', models.CharField(blank=True, max_length=180, null=True, verbose_name='Formulario')),
                ('Url', models.CharField(blank=True, max_length=180, null=True, verbose_name='Url')),
                ('Observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('IDRoles', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Sistema', models.DateTimeField(auto_now_add=True)),
                ('Detalle', models.CharField(blank=True, max_length=120, null=True, verbose_name='Detalle')),
                ('Observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos_Asignados',
            fields=[
                ('IDPermisos_Asignados', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Sistema', models.DateField(auto_now_add=True)),
                ('Permiso', models.IntegerField(default=0, null=True)),
                ('IDPermisos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.permisos')),
                ('IDRoles', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.roles')),
            ],
        ),
    ]
